# Importado en static-deploy.md
# Este archivo se extrae como un archivo separado para que Renovate pueda actualizar las versiones de las acciones
#
#region contenido
# Flujo de trabajo simple para desplegar contenido estático en GitHub Pages
name: Desplegar en GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configurar Pages
        uses: actions/configure-pages@v5
      
      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
#endregion contenido
